# Generated by Django 4.2.2 on 2023-06-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('about_info', models.CharField(blank=True, max_length=500, null=True)),
                ('user_picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/')),
                ('user_cv', models.FileField(blank=True, null=True, upload_to='user_cv/')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='wavingLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag Lines',
            },
        ),
    ]
