# Generated by Django 4.2.2 on 2023-06-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0002_userinformations_banner_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformations',
            old_name='first_Name',
            new_name='first_name',
        ),
    ]
