# Generated by Django 4.2.2 on 2023-06-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0003_rename_first_name_userinformations_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavinglines',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio_server.userinformations'),
            preserve_default=False,
        ),
    ]
