# Generated by Django 4.2.2 on 2023-06-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0004_wavinglines_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='about_info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
