# Generated by Django 4.2.2 on 2023-06-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0006_alter_userinformations_about_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
