# Generated by Django 4.2.2 on 2023-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0008_userinformations_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='interest',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
