# Generated by Django 4.2.2 on 2023-06-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0009_alter_userinformations_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
