# Generated by Django 4.2.2 on 2023-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0011_usereducation_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='specific_degree',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
