# Generated by Django 4.2.2 on 2023-06-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0012_usereducation_specific_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('email_link', models.CharField(blank=True, max_length=200, null=True)),
                ('google_scholar_link', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_server.userinformations')),
            ],
            options={
                'verbose_name': 'User Socials Urls',
            },
        ),
    ]
