# Generated by Django 4.2.2 on 2023-06-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0014_remove_socialurls_email_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_icon_picture', models.ImageField(null=True, upload_to='skill_icons/')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_server.userinformations')),
            ],
            options={
                'verbose_name': 'User Skills',
            },
        ),
    ]
