# Generated by Django 4.2.2 on 2023-06-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0017_alter_userskills_skill_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Publication Type',
            },
        ),
        migrations.CreateModel(
            name='UserPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=200)),
                ('publication_in', models.CharField(max_length=200)),
                ('publishers_name', models.CharField(max_length=500, null=True)),
                ('citation_link', models.CharField(max_length=200, null=True)),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_server.publicationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_server.userinformations')),
            ],
            options={
                'verbose_name': 'User Publication',
            },
        ),
    ]
