# Generated by Django 4.2.2 on 2023-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0018_publicationtype_userpublications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublications',
            name='picture',
            field=models.ImageField(null=True, upload_to='user_publications/'),
        ),
        migrations.AddField(
            model_name='userpublications',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpublications',
            name='wieght',
            field=models.IntegerField(default=1),
        ),
    ]
