# Generated by Django 4.2.2 on 2023-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0019_userpublications_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpublications',
            name='picture',
            field=models.ImageField(default='user_publications/default.png', null=True, upload_to='user_publications/'),
        ),
    ]
