# Generated by Django 4.2.2 on 2023-06-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0020_alter_userpublications_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpublications',
            old_name='wieght',
            new_name='weight',
        ),
    ]
