# Generated by Django 4.2.2 on 2023-06-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0021_rename_wieght_userpublications_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDistinctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinction_title', models.CharField(max_length=150)),
                ('distinction_description', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_server.userinformations')),
            ],
            options={
                'verbose_name': 'User Distinction',
            },
        ),
    ]
