# Generated by Django 4.2.2 on 2023-07-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0023_uservolunteeringexperiences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservolunteeringexperiences',
            old_name='organization',
            new_name='designation_and_organization',
        ),
    ]
