# Generated by Django 4.2.2 on 2023-07-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_server', '0024_rename_organization_uservolunteeringexperiences_designation_and_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='location_maps',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
